# Generated by Django 3.1.5 on 2021-01-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210126_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPR_d07k_f10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Ф1.0Р7.1 Восстановлено на учет в числе ППЛ',
                'verbose_name_plural': 'Ф1.0Р7.1 Восстановлены на учет в числе ППЛ',
            },
        ),
        migrations.CreateModel(
            name='SPR_d08_f10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Ф1.0Р8 Преступление предотвращено',
                'verbose_name_plural': 'Ф1.0Р8 Преступления предотвращены',
            },
        ),
        migrations.CreateModel(
            name='SPR_gas_org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Код ГАСОРГ')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование ГАСОРГ')),
            ],
            options={
                'verbose_name': 'Ф1.0Р3 ГАС Орган',
                'verbose_name_plural': 'Ф1.0Р3 ГАС Органы',
            },
        ),
        migrations.AlterModelOptions(
            name='spr_d01_f10',
            options={'verbose_name': 'Ф1.0Р1 Код территориального органа', 'verbose_name_plural': 'Ф1.0Р1 Коды территориальных органов'},
        ),
        migrations.AlterModelOptions(
            name='spr_d02_f10',
            options={'verbose_name': 'Ф1.0Р2 Учесть', 'verbose_name_plural': 'Ф1.0Р2 Учести'},
        ),
        migrations.AlterModelOptions(
            name='spr_d1o_f10',
            options={'verbose_name': 'Ф1.0Р1 Орган', 'verbose_name_plural': 'Ф1.0Р1 Органы'},
        ),
        migrations.AlterModelOptions(
            name='spr_d3o_f10',
            options={'verbose_name': 'Ф1.0Р3 Вид', 'verbose_name_plural': 'Ф1.0Р3 Виды'},
        ),
        migrations.AlterField(
            model_name='spr_d1o_f10',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование'),
        ),
    ]
